# Generated by Django 6.0.2 on 2026-03-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cc_handle',
            new_name='codechef',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cf_handle',
            new_name='codeforces',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lc_handle',
            new_name='leetcode',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profiles/'),
        ),
    ]
